### ISSUE TITLE
Broken by new Purple Air API

### ISSUE THREAD

**Issue by danswett** [dclaar/purple_air#17]
Alas the new purple air API change has broken this wonderful integration. 

New API requires an API key. 

Will try to find time to poke at this myself, but wanted to raise the issue as well since both of my M5Sticks are now broken.

**Comment by dclaar** [comment]
You will need to email purple air for your own API key.

I will upload a fix shortly--O(days), not O(hours)--just need to update the docs a bit, make sure tests still pass.

**Comment by danswett** [comment]
Thank you!!

**Comment by dclaar** [comment]
As noted, you will need an API read key, but should be fixed!

Files changed:
```
 README.md            | 30 ++++++++++++++++++++++--------
 copy_for_web.py      | 23 ++++++++++++++---------
 copy_to_stick.md     | 24 ++++++++++++++++--------
 flash/apps/WebAQI.py | 25 ++++++-------------------
 flash/aqi.py         |  6 ++++--
 flash/test_WebAQI.py | 23 +++++------------------
 6 files changed, 67 insertions(+), 64 deletions(-)
```

Really, you need to copy these new versions:
```
 flash/apps/WebAQI.py
 flash/aqi.py
```
And modify your `aqi_web.json`, adding the comma and the `read_api_key` bit:

{"name": 0, "correction_index": 2, "sensor_location": "38889", "brightness": 2`, "read_api_key": "########-####-####-####-############"`}

**Comment by danswett** [comment]
Thank you!!
