### ISSUE TITLE
Suggest making refresh interval configurable

### ISSUE THREAD

**Issue by danswett** [dclaar/purple_air#18]
The current refresh interval is every 50 seconds. This means that the device calls the GetSensors API around 1,728 times per day, and PurpleAir now charges 5 "points" per call to this API. This means you should be burning around 8,640 points/day, but in my experience (looking at my PurpleAir account) I was only being charged around 7,500/day.

With the 1M "starter points" you get from PurpleAir (I never even knew they charged for the API until I finally got around to trying to debug why my M5Stick is returning a 402) you'll run through them in about 130 days.

It would be great if it were easier to configure the update interval so you could decide how quickly you wanted to burn though the points.

Thanks for listening!

**Comment by dclaar** [comment]
What?? They do? Shouldn't be too hard.

**Comment by dclaar** [comment]
Purple Air claims that you [don't have to pay for your own data](https://community.purpleair.com/t/api-pricing/4523), although _this is not yet automated_.  It also appears that points _do not renew_ (it's "x points", **not** "x points/month", so increasing the interval just kicks the can down the road, and it will fail at some random point in the future.

On the software side of things, I'm kind of out of buttons. Adding this would require implementing a new layer:

1. Push button:
2. Display menu: brightness, correction, refresh

For refresh, I'd either need to choose intervals to cycle through (and I don't have a good idea of what to pick), or do something like digital clocks: 

1. Choose 1s, 
2. Set. 
3. Choose 10s
4. Set. 
5. Choose 100s. 
6. Set.
7. Either timeout, or figure out some button combination to end.

I'm currently not inclined to go to all that work for something that will be set once or twice, and _doesn't actually solve the problem_, given the non-renewal of points.

The interval is currently hard-coded into WebAQI.py:
```
  def __init__(self):
    self.config_file = CONFIG_FILE
    self.url_template = URL_TEMPLATE
    self.pm2_5_atm = None
    self.pm2_5_cf_1 = None
    self.humidity = None
    self.seconds_between = 50
```
I could change it to be in the JSON file, but that's not really "easier", it just moves it.

Let me know what you think!

**Comment by danswett** [comment]
Thanks - totally agree RE: kicking it down the road, their rules being half-baked, and in general this whole thing just making a mess out of using their API. Also irritating that my sensor reporting data into their system doesn't "generate points" for me (although I think they've claimed this will change). Maybe I'll just switch over to your other program to pull the data locally.

I don't think it needs to be a button - happy to change this in the WebAQI.py - thanks for the pointer!

**Comment by dclaar** [comment]
"Resistance is futile" -- closing after research & talking to reporter as "we hope purple air gets their act together". :)
