### ISSUE TITLE
AQI never updates for WebAQI

### ISSUE THREAD

**Issue by danswett** [dclaar/purple_air#3]
**Setup:**
1. App is installed using copy_for_web.py
2. I swapped lines 183 and 184 in aqi.py so correction "N" is the default

**Repro:**
1. Run WebAQI.py

**Actual:**
1. Boots normally and shows AQI with correct color background. Heart icon and chase flash as expected
2. AQI never updates

**Expected:**
AQI updates

**Other observations:**
1. CTRL+C from console either shows:
Traceback (most recent call last):
  File "main.py", line 48, in <module>
  File "main.py", line 36, in main
  File "aqi.py", line 351, in Run
  File "aqi.py", line 309, in GetData
  File "m5stickc.py", line 237, in GetURI
  File "libs/urequests.py", line 86, in request

or that it's waiting (line 387 in aqi.py)

2. Value is always updated correctly when the app boots (verified by CTRL+C, CTRL+D to soft reboot and value will always change)

**Comment by dclaar** [comment]
Hmm. So it doesn't. Looking.

**Comment by dclaar** [comment]
So the local web site actually changes the color every time the AQI changes, using a gradient function.
I have not implemented that for the correction modes. So "if aqi changed and color changed": doesn't trigger.
It should be "if aqi changed **or** color changed":

Fixed.

**Comment by dclaar** [comment]
P.S. Thanks for finding these so fast!

You know, I always thought that I should write unit tests for this stuff.

**Comment by danswett** [comment]
Always happy to find bugs - thanks for all your work on this, I really
appreciate it!
